### ISSUE TITLE
Input key events with Shizuku not working if obfuscation enabled

### ISSUE THREAD

**Issue by godzellax** [keymapperorg/KeyMapper#1043]
**Developer TODO (don't remove)**
- [ ] create new branch. put issue number at start of name if not a very quick fix.
- [ ] write tests. put issue number in comment
- [ ] update documentation
- [ ] merge and delete branch (don't squash because want commit history to see why I made changes)

**Discord message link/email recipient**

**Describe the bug**
Input key event not working when grant Shuzuku permission for Keynapper
**To Reproduce**
Activate Keymapper in Shizuku
Map any hardware key of any connected device to any key input event action
Press the mapped button

Upload a backup of your keymaps. (Follow the guide here.)[https://keymapperorg.github.io/KeyMapper/user-guide/backup-restore]

**Expected behavior**
The selected action should be performed when the mapped button pressed
**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [Samasung Galaxy Note 4]
 - Android version: [Android 6.1]

**Additional context**
Phone rooted and root permission granted. The issue happen regardless of the selected keyboard type in phone settings

**Comment by godzellax** [comment]
I tried on my Android TV 7.1.1 and faced the same issue although Shuzuku is activated via adb and keymapper permission granted and even when keymapper keyboard selected the issue will remain as long as Shizuku is working and the pemission granted unless If I disable the permission in Shizuku everything will work fine as expected

**Comment by sds100** [comment]
Interesting, can you send a bug report. Follow this guide https://docs.keymapper.club/report-issues/

**Comment by godzellax** [comment]
Please find the bug report
https://drive.google.com/file/d/1YZKNU1-Py4K_p1I0_UReqor8V5EPd6-T/view?usp=drivesdk

**Comment by sds100** [comment]
So it looks like Key Mapper is performing the action - it just isn't working the way it is expecting. If you use a keycode other than KEYCODE_DPAD_DOWN as your action - e.g KEYCODE_A does the letter A get typed in when you perform the action?

**Comment by godzellax** [comment]
Seems nothing is working even when activate root shell option in action
Please find the new bug report
https://drive.google.com/file/d/1Z-Y0izC7_xNUYVr_MNfxzcAS7cLsKISz/view?usp=drivesdk

**Comment by sds100** [comment]
Strange, but if you use the Key Mapper keyboard it does work? What are you wanting to happen when Key Mapper inputs KEYCODE_DPAD_DOWN?

**Comment by godzellax** [comment]
No it will not work even when you select key mapper keyboard. It works only when normally disable shizuku support and select key mapper keyboard.
I want to use shizuku so I can use any keyboard but the problem when I use shizuku all input key events stop working even when I select key mapper keyboard.
The same issue exactly happen to my android TV also.
Please help me Sir.

**Comment by godzellax** [comment]
KEYCODE_DPAD_DOWN just for test reason. So I can navigate down on my phone app menu same as I can when using hat switch.

**Comment by sds100** [comment]
Oh okay. What if you use KEYCODE_A instead of KEYCODE_DPAD_DOWN? I just want to see if the letter A is typed in when you use that action.

**Comment by godzellax** [comment]
Notthing typed I already tested that and sent you a second report bug covered the case.

**Comment by godzellax** [comment]
I mapped my ipega gamepad X button to keycode a from key mapper input event action and test the button in gamepad tester app and found the following:

1. Without shizuku support and with keymapper keyboard the app detect the button as keycode a and if I change to another keyboard the app will no more detect anything when I press X which is normal
2. With shizuku support and with any keyboard selected even with keymapper keyboard, the app detect nothing when I press X
3. 
Please note Accessibilty services is working fine and Im familiar with your app and what im doing

**Comment by godzellax** [comment]
Gamepad also tested on my Android TV and also my remote control and found the same result

**Comment by sds100** [comment]
Can you create a "key event" action with KEYCODE_A and set the _from device_ to "Virtual". Then see if that action works? Send a bug report again as well.

**Comment by godzellax** [comment]
Same result and same issue
https://drive.google.com/file/d/1_NFzfrTqfMeYwv5ysuyzbvkoKJgS6K9Z/view?usp=drivesdk

**Comment by sds100** [comment]
> Same result and same issue
> https://drive.google.com/file/d/1_NFzfrTqfMeYwv5ysuyzbvkoKJgS6K9Z/view?usp=drivesdk

What! That is really weird. I have never heard from anyone that ALL of these methods don't work. Do any other old versions of key mapper work? Can you send a screen recording of everything you are doing just to make sure there isn't some misunderstanding.

**Comment by godzellax** [comment]
All of these methods not working when using shizuku and everything was working fine without shizuku. The issue only occured recently after version 2.4 when your app start supporting shizuku.
Im using version 2.4.2 and everything working fine without shizuku support but once I enable keymapper in shizuku every thing will stop working except the mapped keys which use accessibilty services such as Go Home action
I'll send you screen recroding asap

**Comment by godzellax** [comment]
Yup that it

**Comment by sds100** [comment]
Oh righht. Okay, in ADB can you do `input keyevent {key code for DPAD_DOWN}` and see if it works?

**Comment by godzellax** [comment]
It works flawlessly

**Comment by sds100** [comment]
> It works flawlessly

And the "use shell" option in Key Mapper doesn't work?

**Comment by sds100** [comment]
> Only working without shizuku

Yeah, okay, So the Shizuku is the only issue. I was really confused earlier because it sounded like other stuff also wasn't working. 😄

**Comment by godzellax** [comment]
Enable keymapper in shizuku and the disaster will happen xd

**Comment by godzellax** [comment]
How you can help me Sir is it a bug or what?
I tried all versions after 2.4 beta all has the same issue

**Comment by sds100** [comment]
I'm going to try and reproduce it on Android 6 and 7 emulators.

**Comment by sds100** [comment]
It works fine for me in Android 6 emulator. Can you send a screen recording

**Comment by sds100** [comment]
I still can't reproduce the issue on Android 6.0 with the same key map as you. If you use a volume button as a trigger and not your controller does it still happen?

**Comment by godzellax** [comment]
The same issue Sir I mapped volum button to "keycode a" and found the same result
Its not because of my phone because on my Android TV the same happening

**Comment by godzellax** [comment]
Please note on my Android TV I have many mapped buttons to many devices like remote control and twin gamepads and all are working fine without shizuku. Enabling shizuku will ruin everything lol...

**Comment by godzellax** [comment]
Please note disable and re-enable accessibilty service neither uninstall and reinstall keymapper is going to fix the issue. I already tested many things trying to fix the issue with no luck.

**Comment by godzellax** [comment]
Maybe its different with Emulators, can you try from your end on real devices.

**Comment by sds100** [comment]
> Maybe its different with Emulators, can you try from your end on real devices.

I don't have any Android 6.0 or 7 real devices but on all my real devices it also works.

**Comment by godzellax** [comment]
How you can help me Sir to solve the issue.
You have seen in your eyes that the issue is happening to me.

**Comment by sds100** [comment]
I'm not sure, is your TV also rooted?

**Comment by godzellax** [comment]
Not rooted Sir, I activate shizuku through adb script

**Comment by sds100** [comment]
Do you have any other Android devices that you can test with?

**Comment by sds100** [comment]
If you uninstall and reinstall Key Mapper does it work?

**Comment by godzellax** [comment]
I dont have right now in my hands but I might check my parents phones. If I do I'll update you.
Can you pin the issue so other users might check on their phones also.

**Comment by godzellax** [comment]
Already uninstall keymapper and reinstall with no luck

**Comment by godzellax** [comment]
I will try to check samsung phone running marshmallow to see whats going on. The phone is not rooted and have never ever installed keymapper before on it so If I find the same issue means old versions of OS not compatible with your new shizuku facility.
I will keep you updated.
Do you have any other suggestions Sir?

**Comment by sds100** [comment]
> I will try to check samsung phone running lolipop to see whats going on. The phone is not rooted and have never ever installed keymapper before on it so If I find the same issue means old versions of OS not compatible with your new shizuku facility. I will keep you updated. Do you have any other suggestions Sir?

I'm not sure. There is something wrong with your setup or the ROM that your phone has. Since it works in the emulator this means that it isn't an issue with _android_ or what I am doing with Key Mapper. There may be some issue or "security feature" with the specific ROM on your phone and TV?

**Comment by godzellax** [comment]
Very wierd however let me check android Lollipop and update you

**Comment by godzellax** [comment]
Please note I have stock rom in my phone and my TV

**Comment by godzellax** [comment]
Really Sir ok I will check the Lollipop phone which has stock rom and never ever rooted before and see the result

**Comment by godzellax** [comment]
Sir your app as well as Shizuku need minimum os 6.0
Any suggestions Sir, can you do something to tell other users to ckeck from their side if that possible

**Comment by sds100** [comment]
GOOD NEWS! I can reproduce it with the _production_ builds of Key Mapper 2.4.2. The debug builds don't have the issue which is why I couldn't reproduce it. 😄 I have an idea what the issue will be and will be fixed in 2.4.3

**Comment by godzellax** [comment]
OMG!!!!
I told you Sir it was not because of my phone neither my TV. Would you please just explain as a brief what was the cause of the issue?
Thank you in advance.

**Comment by Zerubel** [comment]
Recording my findings from the discussion in discord earlier:
Device info: Samsung Galaxy A51 (SM-A51U1, carrier unlocked, no root)
Android 12, Samsung One UI v4.1
Shizuku v12.6, adb 
Shizuku is running, Key Mapper is authorized
Key Mapper v2.4.2
Key Mapper confirms Shizuku is installed and started

Devices used to test:
8bitdo SN30pro game controller, bluetooth connection
8bitdo Zero 2 game controller, bluetooth connection
hardware volume up button

tests were conducted first with SN30pro, which has a .kl file, and second with the Zero 2, which does not have a .kl file.
Set button "B" to input "KEYCODE_BUTTON_A" (key code 96)- no response or recognition from gamepad tester app or when used to navigate system. Other gamepad buttons still worked as intended or with previously set bindings.
Set button "B" to input "KEYCODE_A" (key code 29) - opened note taking app. No response or input detected by app or system.
Final test: set volume up hardware key to "KEYCODE_A" (key code 29) and opened note taking app - no response detected by app or system. Volume down still works as intended.

**Comment by godzellax** [comment]
I understood Sir, I hope the next building will be soon and the issue will be resolved.
Thank you Sir you are so cute.

**Comment by sds100** [comment]
fixed

**Comment by Wisehh** [comment]
@godzellax does the commit work for you? I just discover this issue and try to install the last released pkg but for me the error still exists.

(Also, thank you so much for this app @sds100. It is absolutely amazing)

**Comment by sds100** [comment]
Oops, I will investigate again. Can you send a bug report https://docs.keymapper.club/report-issues/.

And thanks! I try to find time to work on it ;)

**Comment by Wisehh** [comment]
> Oops, I will investigate again. Can you send a bug report https://docs.keymapper.club/report-issues/.
> 
> And thanks! I try to find time to work on it ;)

 Done! I send you via Discord-debug channel. Please tell me if you need something more (github or Discord it's fine for me).

**Comment by sds100** [comment]
The issue is unrelated.

**Comment by godzellax** [comment]
Issue resolved for me with new version 2.4.3
Thank you so much everyone
