### ISSUE TITLE
Not in Phone Call Constraint Not Working

### ISSUE THREAD

**Issue by githubsterer** [keymapperorg/KeyMapper#1519]
**Developer TODO (don't remove)**
- [ ] update documentation

Added this constraint to a key map but does not prevent the action from running.

**Comment by githubsterer** [comment]
Further testing showing very bizarre behavior. When Not in Phone Call is the only constraint, it works. When it is combined with another constraint like App Not in Foreground,  it only works with the AND condition not the OR condition, even though the Phone app has nothing to do with OneUI Home.

**Comment by githubsterer** [comment]
One last thing. I just added a third constraint to the list, and the same thing as before, where only the AND condition makes then work, where the OR condition does not. 

![Image](https://github.com/user-attachments/assets/e4b8d638-90f7-404c-9b55-567f842314a2)

**Comment by jambl3r** [comment]
Reproduced with Google Pixel 8a, Key Mapper 3.0.0 alpha 13

**Comment by jambl3r** [comment]
Could you verify whether the phone call constraint works without the OneUI constraint? And provide an example screenshot of the key maps. I'm having trouble reproducing your issue.

**Comment by githubsterer** [comment]
Yes, unrelated to that other constant. This key map does not allow volume controls during a phone call. 

![Image](https://github.com/user-attachments/assets/4f1fafb8-c8f5-4105-aaba-ca0c517cf39b)

**Comment by jambl3r** [comment]
We just made an improvement to the phone call detection #1545 so this (may) be fixed but can't know for sure.
When you say phone call, do you mean an ordinary cell phone call or something via another app like WhatsApp?

**Comment by jambl3r** [comment]
This APK should contain the fix

https://cdn.discordapp.com/attachments/717532902346326088/1351350135237640252/keymapper-2.8.4-ci.205.apk?ex=67da0e63&is=67d8bce3&hm=ca1ffb24c229be956630ac2b974584d1f7da4663fbed638e2e236ec4b81ac1ee&

It's a Continuous Integration (CI) build so will install as its own separate app, with its own permissions, service, key maps, etc.

**Comment by githubsterer** [comment]
Not familiar with that term, so I should install this and test and then discard? Testing now.

**Comment by jambl3r** [comment]
You can uninstall it after if you want but it won't hurt to keep it. Maybe just disable the accessibility service when you're not actively testing it so it doesn't interfere with anything else

The only practical difference is that the package name is `io.github.sds100.keymapper.ci` so may impact you making any intents

**Comment by githubsterer** [comment]
I have GREAT NEWS. It works!!! 

Tested both the Phone app as well as Whatsapp and it works exactly as you would want and expect. Congrats! 

Now please tackle the media issue. If you can please also deal with the double vibration and volume issue with multiple key maps on the same key, then the basic usability issues will be stable enough to deploy all day for more extensive testing. 

I guess I'll delete this special app and wait for another one to test for you whenever you're ready.

**Comment by githubsterer** [comment]
So I uninstalled that test version in order to update to 2.8.3 to test the side button, but it's not letting me. 

![Image](https://github.com/user-attachments/assets/e575160e-f428-4acc-ae38-13ed4cdf4f64)

**Comment by jambl3r** [comment]
Media issue should be fixed in that build. The other issues are much more complicated so won't be fixed for many months

**Comment by jambl3r** [comment]
> So I uninstalled that test version in order to update to 2.8.3 to test the side button, but it's not letting me do so from the APK. Not sure where the conflict is if I deleted the other version.

Builds you get from GitHub and builds you get from Google Play are not really the same app, so you will not be able to update between them

**Comment by githubsterer** [comment]
Then I'll have to wait until you put 2.8.3 on play store because you can't get the side button app any other way. Let me know when you do that, as well as the fix for media.

**Comment by githubsterer** [comment]
Can you get that up on play?

**Comment by jambl3r** [comment]
2.8.3 is already released, and cannot be changed retrospectively. You'll have to wait for 2.8.4 for further fixes.

2.8.3 is under review by Google and will be up on the store whenever they approve it.

**Comment by githubsterer** [comment]
Understand both your comments but simply cannot test all three issues together without them being in the same version I have, so I'll just have to wait. So far, all I can report back to you in that the phone constraint appears fixed. Media and side button testing will have to wait.

**Comment by githubsterer** [comment]
> Media issue should be fixed in that build

If the CI build you sent me last night includes the code from 2.8.3 then I can tell you the media constraint is not yet fixed because I tested that as well as the phone.

**Comment by jambl3r** [comment]
I think we have established that this is fixed

**Comment by githubsterer** [comment]
> 2.8.3 is under review by Google and will be up on the store for beta testers whenever they approve it.

FYI still not up yet days later, interestingly the 2.8.2 says it was available on Play Store on the same date you released it on GitHub March 12 but that just may be because you uploaded it there later?

**Comment by jambl3r** [comment]
Phone call detection relies on apps either using the telephony API (not many actually do) or prioritising the voice call volume stream (almost all do).

The few that don't are really just poorly programmed, at this point there isn't much more one could look out for to identify 'a call in progress'.

**Comment by githubsterer** [comment]
I was hoping that your future 2.8.4 note about making it work with more phone apps might help. I suppose if not there's always the app specific nuclear option. I'm also hoping you release 2.8.4 very soon so we can finally have the media fix and also a full fix of the side button.
